server:
  port: 9001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false        #false表示自己就是注册中心，职责维护服务实例
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
